[tasks.build]
run = [
    "uv run --active python -m build",
    "uv pip install ./dist/ft_package-0.0.1.tar.gz",
    "uv pip install ./dist/ft_package-0.0.1-py3-none-any.whl",
    "uv pip show -v ft_package"
]

[tasks.docker]
run = [
    "docker run --rm -it -v $(pwd):/app -w /app python:3.10 bash",
    # "pip install --upgrade pip",
    # "pip install build",
    # "python -m build",
    # "pip install ./dist/ft_package-0.0.1.tar.gz",
    # "pip install ./dist/ft_package-0.0.1-py3-none-any.whl",
    # "pip show -v ft_package"
]

[tasks.clean]
run = [
    "rm -rf dist",
    "rm -rf ft_package.egg-info",
    "uv pip uninstall ft_package"
]