[tools]
python = "3.10"
uv = "latest"

[env]
_.python.venv = { path = ".venv", create = true }

[shell_alias]
norminette = "flake8" # alias norminette=flake8

[tasks.norminette]
run = "flake8 --exclude=.venv ."
