[project]
name = "42sp-python-piscine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "build>=1.3.0",
    "flake8>=7.3.0",
    "tqdm>=4.67.1",
]
